version: "3.7"

services:
  gateway:
    command: "npm run start:dev"
    volumes: 
      - ./gateway:/app
    env_file: 
      - develop.env

  dispatcher:
    command: "npm run start:dev"
    volumes: 
      - ./dispatcher:/app
    env_file: 
      - develop.env

  clickhouse_worker:
    command: "npm run start:dev"
    volumes: 
      - ./clickhouse_worker:/app
    env_file: 
      - develop.env